[tasks]
build-install     = "gh extension remove gh-reassign-reviewer || true && go build . && gh extension install ."
extension-install = "gh extension install ryo246912/gh-reassign-reviewer"
lint-go           = "golangci-lint run"
lint-action       = "actionlint -ignore 'SC2016:' || true && ghalint run || true && zizmor --pedantic --gh-token=$(gh auth token) --min-severity=low .github/workflows"
run               = "go run ."

[tools]
actionlint                     = "1.7.7"
"aqua:suzuki-shunsuke/ghalint" = "1.5.1"
golangci-lint                  = "2.1.6"
"pipx:zizmor"                  = "1.9.0"
