name: auto-author-assign
on:
  pull_request:
    types:
      - opened
      - reopened
  issues:
    types:
      - opened
      - reopened

permissions: {}

jobs:
  assign:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      contents: read
      repository-projects: read
      issues: write
      pull-requests: write
    steps:
      - name: pull request auto assignee
        if: ${{ toJSON(github.event.pull_request.assignees) == '[]' && ! endsWith(github.actor, '[bot]') }}
        run: gh pr edit "$NUMBER" --add-assignee "$ASSIGNEE"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          ASSIGNEE: ${{ github.event.pull_request.user.login }}

      - name: issue auto assignee
        if: ${{ toJSON(github.event.issue.assignees) == '[]' }}
        run: gh issue edit "$NUMBER" --add-assignee "$ASSIGNEE"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          ASSIGNEE: ${{ github.event.issue.user.login }}
