name: lint-action
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/*"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*"

permissions: {}

concurrency:
  group: lint-action-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
        with:
          version: 2024.12.24
          install_args: "actionlint"
      - name: actionlint
        run: |
          actionlint \
          -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}' \
          -ignore 'SC2016:'
  ghalint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
        with:
          version: 2024.12.24
          install_args: "aqua:suzuki-shunsuke/ghalint"
      - name: ghalint
        run: ghalint run
        env:
          GHALINT_LOG_COLOR: always
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@5cb1df66ed5e1fb3c670ea0b62fd17a76979826a # v2.3.1
        with:
          version: 2024.12.24
          install_args: "pipx:zizmor"
      - name: zizmor
        run: zizmor --pedantic --format=github --min-severity=low .github/workflows
        env:
          GH_TOKEN: ${{ github.token }}
