name: lint-action
on:
  push:
    paths:
      - ".github/workflows/*.yaml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/*.yaml"

permissions: {}

concurrency:
  group: lint-action-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
        with:
          version: 2024.12.24
          experimental: true
          tool_versions: |
            pipx:zizmor 1.9.0
      - run: zizmor --pedantic --format=github --min-severity=low .github/workflows
        env:
          GH_TOKEN: ${{ github.token }}
